// app/layout.tsx
import { Geist, Geist_Mono } from "next/font/google";
import FontAwesomeConfig from "./fontawesome";
import "./globals.css";
import QueryClientWrapper from "./QueryClientWrapper"; // Import the client-side wrapper

// Load custom fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Static metadata for the app
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <FontAwesomeConfig />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Use the client-side QueryClientWrapper */}
        <QueryClientWrapper>{children}</QueryClientWrapper>
      </body>
    </html>
  );
}
